PRO_DATA_DIR = "../"
DATA_DIR = PRO_DATA_DIR + "/data"
OUT_DATA_DIR = PRO_DATA_DIR + "/out_data"
OUT_FIG_DIR = PRO_DATA_DIR + "/out_fig"
MODEL_DIR = PRO_DATA_DIR + "model"
TRAIN_FILE = DATA_DIR + "/Sept-2019-ML-processing.csv"
